# # OPENAI SDK

# # import OpenAI client class
# from openai import OpenAI

# # read API key from config file
# from config import OPENAI_API_KEY

# # create client that commiunicates with OpenAI
# client = OpenAI(api_key=OPENAI_API_KEY)

# # API Request. asking OpenAI to generate a response
# response = client.responses.create(

#     # choose which model should answer
#     model = "gpt-4.1-mini",

#     # this is the prompt
#     input = "Explain what an API is."
# )

# # output_text gives you the generated answer
# print(response.output_text)

# USING LANGCHAIN

from langchain_openai import ChatOpenAI
from config import OPENAI_API_KEY

# instead of creating openai client, create Langchain LLM object
llm = ChatOpenAI(
    model = "gpt-4.1-mini",
    api_key=OPENAI_API_KEY,
)

# Response. invoke = Langchain's methods :"run this model on the given input"
response = llm.invoke("What is Retrieval-Augmented Generation")

# .content gives the text generated by the model
print(response.content)
